#!/usr/bin/env bash
# Install `kilix-bonsai` as a command.
#
# The command is a small launcher that runs the tool from this checkout, the
# same shape kilix-tui-utils uses: updating is a `git pull` rather than a
# reinstall, and the checkout stays the single source of truth for what a model
# is. Nothing is downloaded here — installing the command and fetching eleven
# gigabytes of weights are separate decisions and should stay that way.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${KILIX_BONSAI_PREFIX:-$HOME/.local}"
BIN="$PREFIX/bin"
TOOLS="kilix-bonsai kilix-bonsai-chat kilix-bonsai-image kilix-bonsai-speech"

die() { printf 'kilix-bonsai: %s\n' "$1" >&2; exit 1; }
shell_quote() {
    printf "'"
    printf '%s' "$1" | sed "s/'/'\\\\''/g"
    printf "'"
}

python_launcher() {
    target="$1"
    quoted_target="$(shell_quote "$target")"
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# Generated by kilix-bonsai/install.sh — edits belong in the checkout.'
    printf 'exec python3 %s "$@"\n' "$quoted_target"
}

command_launcher() {
    target="$1"
    quoted_target="$(shell_quote "$target")"
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# Generated by kilix-bonsai/install.sh — edits belong in the checkout.'
    printf 'exec %s "$@"\n' "$quoted_target"
}

usage() {
    cat <<'EOF'
usage: install.sh [--uninstall]

  --uninstall  remove launchers generated for this checkout; retain any
               launcher whose contents were changed after installation
EOF
}

case "$PREFIX" in
  /*) ;;
  *) die "KILIX_BONSAI_PREFIX must be an absolute path" ;;
esac

command -v python3 >/dev/null 2>&1 || die "python3 is required"

uninstall=0
case "${1:-}" in
  '') ;;
  --uninstall) uninstall=1; shift ;;
  -h|--help) usage; exit 0 ;;
  *) usage >&2; exit 2 ;;
esac
[ "$#" -eq 0 ] || { usage >&2; exit 2; }

if [ "$uninstall" = 1 ]; then
    removed=0
    retained=0
    for command_name in $TOOLS; do
        launcher="$BIN/$command_name"
        [ -e "$launcher" ] || continue
        expected="$(python_launcher "$HERE/tools/$command_name/main.py")"
        if [ -f "$launcher" ] && [ "$(cat -- "$launcher")" = "$expected" ]; then
            rm -f -- "$launcher"
            removed=$((removed + 1))
        else
            printf 'kilix-bonsai: retain modified launcher %s\n' "$launcher" >&2
            retained=$((retained + 1))
        fi
    done
    launcher="$BIN/bonsai-cpu"
    if [ -e "$launcher" ]; then
        expected="$(command_launcher "$HERE/bonsai-cpu/bin/bonsai-cpu")"
        if [ -f "$launcher" ] && [ "$(cat -- "$launcher")" = "$expected" ]; then
            rm -f -- "$launcher"
            removed=$((removed + 1))
        else
            printf 'kilix-bonsai: retain modified launcher %s\n' "$launcher" >&2
            retained=$((retained + 1))
        fi
    fi
    printf 'kilix-bonsai: removed %d launchers from %s\n' "$removed" "$BIN"
    [ "$retained" -eq 0 ] || die "$retained modified launcher(s) retained"
    exit 0
fi

[ -f "$HERE/tools/kilix-bonsai/main.py" ] || die "this checkout is incomplete"
[ -x "$HERE/bonsai-cpu/bin/bonsai-cpu" ] \
  || die "this checkout is missing the bundled bonsai-cpu runtime"

mkdir -p -- "$BIN" || die "could not create $BIN"

# The store and the three interfaces it launches. Each is a separate command
# so it can be run directly, put in a desktop menu, or resolved by the
# launcher.
installed=0
for command_name in $TOOLS; do
    target="$HERE/tools/$command_name/main.py"
    [ -f "$target" ] || { printf '  skip %s (missing)\n' "$command_name"; continue; }
    launcher="$BIN/$command_name"
    tmp="$launcher.tmp.$$"
    python_launcher "$target" >"$tmp"
    chmod 0755 "$tmp"
    mv -f "$tmp" "$launcher"
    installed=$((installed + 1))
done

# CPU chat is part of this repository but keeps its own package and direct
# command. Publish it beside the store interfaces so a single installation
# produces every command the launcher can delegate to.
target="$HERE/bonsai-cpu/bin/bonsai-cpu"
launcher="$BIN/bonsai-cpu"
tmp="$launcher.tmp.$$"
command_launcher "$target" >"$tmp"
chmod 0755 "$tmp"
mv -f "$tmp" "$launcher"
installed=$((installed + 1))

printf 'kilix-bonsai: installed %d commands into %s\n' "$installed" "$BIN"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *) printf 'kilix-bonsai: note — %s is not on PATH\n' "$BIN" ;;
esac
