#!/usr/bin/env bash
# Install `kilix-bonsai` as a command.
#
# The command is a small launcher that runs the tool from this checkout, the
# same shape kilix-tui-utils uses: updating is a `git pull` rather than a
# reinstall, and the checkout stays the single source of truth for what a model
# is. Nothing is downloaded here — installing the command and fetching eleven
# gigabytes of weights are separate decisions and should stay that way.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${KILIX_BONSAI_PREFIX:-$HOME/.local}"
BIN="$PREFIX/bin"

die() { printf 'kilix-bonsai: %s\n' "$1" >&2; exit 1; }

case "$PREFIX" in
  /*) ;;
  *) die "KILIX_BONSAI_PREFIX must be an absolute path" ;;
esac

command -v python3 >/dev/null 2>&1 || die "python3 is required"
[ -f "$HERE/tools/kilix-bonsai/main.py" ] || die "this checkout is incomplete"

mkdir -p -- "$BIN" || die "could not create $BIN"

# The store, and the three interfaces it launches. Each is a separate command
# so it can be run directly, put in a desktop menu, or resolved by the
# launcher — which prefers an installed command over this checkout.
TOOLS="kilix-bonsai kilix-bonsai-chat kilix-bonsai-image kilix-bonsai-speech"

installed=0
for command_name in $TOOLS; do
    target="$HERE/tools/$command_name/main.py"
    [ -f "$target" ] || { printf '  skip %s (missing)\n' "$command_name"; continue; }
    launcher="$BIN/$command_name"
    tmp="$launcher.tmp.$$"
    cat >"$tmp" <<LAUNCHER
#!/bin/sh
# Generated by kilix-bonsai/install.sh — edits belong in the checkout.
exec python3 "$target" "\$@"
LAUNCHER
    chmod 0755 "$tmp"
    mv -f "$tmp" "$launcher"
    installed=$((installed + 1))
done

printf 'kilix-bonsai: installed %d commands into %s\n' "$installed" "$BIN"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *) printf 'kilix-bonsai: note — %s is not on PATH\n' "$BIN" ;;
esac
