#!/usr/bin/env bash
# Install `kilix-bonsai` as a command.
#
# The command is a small launcher that runs the tool from this checkout, the
# same shape kilix-tui-utils uses: updating is a `git pull` rather than a
# reinstall, and the checkout stays the single source of truth for what a model
# is. Nothing is downloaded here — installing the command and fetching eleven
# gigabytes of weights are separate decisions and should stay that way.
set -euo pipefail

HERE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PREFIX="${KILIX_BONSAI_PREFIX:-$HOME/.local}"
BIN="$PREFIX/bin"

die() { printf 'kilix-bonsai: %s\n' "$1" >&2; exit 1; }

case "$PREFIX" in
  /*) ;;
  *) die "KILIX_BONSAI_PREFIX must be an absolute path" ;;
esac

command -v python3 >/dev/null 2>&1 || die "python3 is required"
[ -f "$HERE/tools/kilix-bonsai/main.py" ] || die "this checkout is incomplete"

mkdir -p -- "$BIN" || die "could not create $BIN"

launcher="$BIN/kilix-bonsai"
tmp="$launcher.tmp.$$"
cat >"$tmp" <<LAUNCHER
#!/bin/sh
# Generated by kilix-bonsai/install.sh — edits belong in the checkout.
exec python3 "$HERE/tools/kilix-bonsai/main.py" "\$@"
LAUNCHER
chmod 0755 "$tmp"
mv -f "$tmp" "$launcher"

printf 'kilix-bonsai: installed %s\n' "$launcher"

case ":$PATH:" in
  *":$BIN:"*) ;;
  *) printf 'kilix-bonsai: note — %s is not on PATH\n' "$BIN" ;;
esac
